[project]
name = "redact"
version = "0.1.0"
description = "On-Device Neural Redaction for Safe LLM Pasting"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=4.8.4",
    "evaluate>=0.4.6",
    "onnx>=1.21.0",
    "onnxruntime>=1.24.4",
    "seqeval>=1.2.2",
    "torch>=2.11.0",
    "transformers>=5.6.0",
    "wandb>=0.26.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
]
