import { getAdapter, HOST_MATCHES, type SiteAdapter } from '@/lib/sites';
import {
  showLoadingIndicator, removeLoadingIndicator,
  showWarnBanner, showBlockModal, showRedactionToast,
} from '@/lib/ui';
import { effectiveSettings, inCooldown, markCooldown } from '@/lib/settings';
import { redactSpans, blockSpans, warnSpans } from '@/lib/redact';
import type { DetectionSpan } from '@/lib/tiers';
import '@/assets/content.css';

// Vite bundles the worker as a separate chunk. `?worker&url` returns the path
// to that chunk (e.g. "/assets/inference-worker-XXXX.js"). We then prepend the
// extension's origin via browser.runtime.getURL — content scripts run in the
// host page's context, so a bare path would resolve against claude.ai, not the
// extension, and 404.
import workerUrlPath from '@/lib/inference-worker.ts?worker&url';

export default defineContentScript({
  matches: HOST_MATCHES,
  cssInjectionMode: 'manifest',
  main() {
    const found = getAdapter();
    if (!found) {
      console.warn('[redact] no adapter for', location.hostname);
      return;
    }
    // Re-bind to a non-null const so closures below don't lose narrowing.
    const adapter: SiteAdapter = found;

    // ── Worker setup ────────────────────────────────────────────────────────
    // MV3 quirk: a content script can't construct a Worker pointing at a
    // chrome-extension:// URL — Chrome blocks it as cross-origin. The
    // workaround: fetch the bundled worker file (allowed because it's in
    // web_accessible_resources), wrap the source in a Blob, and spawn from
    // the Blob URL. Blob inherits the host page's origin, so the cross-origin
    // restriction doesn't apply to the constructor.
    let worker: Worker | null = null;
    let workerInitPromise: Promise<Worker> | null = null;
    let nextRequestId = 1;
    const pendingRequests = new Map<number, (r: { detections?: DetectionSpan[]; error?: string }) => void>();

    async function getWorker(): Promise<Worker> {
      if (worker) return worker;
      if (workerInitPromise) return workerInitPromise;

      workerInitPromise = (async () => {
        // Cast: the worker chunk path is generated by Vite at build time and isn't
        // in WXT's static PublicPath union. Same for /model/ and /wasm/ below — the
        // model dir holds the directory base path (transformers.js appends filenames),
        // and /wasm/ is populated by the vite-plugin-static-copy build step.
        const getURL = (p: string) => browser.runtime.getURL(p as never);
        const workerUrl = getURL(workerUrlPath);
        const response = await fetch(workerUrl);
        const code = await response.text();
        const blob = new Blob([code], { type: 'text/javascript' });
        const blobUrl = URL.createObjectURL(blob);

        const w = new Worker(blobUrl, { type: 'module' });

        w.addEventListener('message', (e: MessageEvent) => {
          const { id, detections, error } = e.data;
          const resolve = pendingRequests.get(id);
          if (!resolve) return;
          pendingRequests.delete(id);
          resolve({ detections, error });
        });

        w.addEventListener('error', (e) => {
          console.error('[redact] worker error:', e);
        });

        w.postMessage({
          type: 'init',
          modelUrl: getURL('/model/'),
          wasmPaths: getURL('/wasm/'),
        });

        worker = w;
        return w;
      })();

      return workerInitPromise;
    }

    async function runInference(text: string): Promise<{ detections?: DetectionSpan[]; error?: string }> {
      const w = await getWorker();
      return new Promise((resolve) => {
        const id = nextRequestId++;
        pendingRequests.set(id, resolve);
        w.postMessage({ type: 'infer', id, text });
      });
    }

    // ── Core handler ────────────────────────────────────────────────────────
    // Runs the model + UI flow on a chunk of pasted text. Returns the final
    // text the caller should insert (possibly redacted), or null if cancelled.
    async function processPasteText(pastedText: string): Promise<string | null> {
      const settings = await effectiveSettings(location.hostname);
      if (!settings.enabled) return pastedText;

      if (!pastedText || pastedText.length < 20) return pastedText;

      showLoadingIndicator();
      let detections: DetectionSpan[] = [];
      try {
        const result = await runInference(pastedText);
        if (result.error) console.error('[redact] inference error:', result.error);
        detections = result.detections || [];
      } catch (err) {
        console.error('[redact] inference threw:', err);
      }
      removeLoadingIndicator();

      const blocks = blockSpans(detections);
      const warns = warnSpans(detections);

      let finalText = pastedText;

      if (blocks.length > 0) {
        const mode = settings.blockBehavior;
        if (mode === 'auto-redact') {
          finalText = redactSpans(pastedText, blocks);
          const result = await showRedactionToast(blocks);
          if (result === 'undo') finalText = pastedText;
        } else if (mode === 'cooldown' && inCooldown(location.hostname, settings.cooldownMinutes)) {
          finalText = redactSpans(pastedText, blocks);
          const result = await showRedactionToast(blocks);
          if (result === 'undo') finalText = pastedText;
        } else {
          const decision = await showBlockModal(pastedText, blocks);
          if (mode === 'cooldown') markCooldown(location.hostname);
          if (decision === 'cancel') return null;
          if (decision === 'redact') finalText = redactSpans(pastedText, blocks);
        }
      }

      if (warns.length > 0 && settings.warnBehavior === 'banner') {
        showWarnBanner(warns, settings.warnAutoDismissSec * 1000);
      }

      return finalText;
    }

    // ── Listener strategy ───────────────────────────────────────────────────
    // We attach at `document` capture phase to catch paste events regardless
    // of which element is focused. Two event types because different editors
    // dispatch different events:
    //
    //   `paste`        — fires on simple <textarea> and most contenteditable
    //                    setups (ChatGPT, Gemini). clipboardData is sync.
    //   `beforeinput`  — fires for *any* programmatic edit including paste
    //                    on Lexical/ProseMirror/Slate editors that swallow
    //                    native paste (Claude). For inputType='insertFromPaste'
    //                    the inserted text is in `event.data`.

    async function onPaste(e: ClipboardEvent) {
      const text = e.clipboardData?.getData('text') || '';
      if (text.length < 20) return;
      e.preventDefault();
      e.stopImmediatePropagation();

      const inputEl = (e.target as HTMLElement) || adapter.findInput();
      const finalText = await processPasteText(text);
      if (finalText === null || !inputEl) return;
      adapter.insertText(inputEl, finalText);
    }

    async function onBeforeInput(e: InputEvent) {
      if (e.inputType !== 'insertFromPaste') return;
      const text = (e as any).data || e.dataTransfer?.getData('text') || '';
      if (text.length < 20) return;
      e.preventDefault();
      e.stopImmediatePropagation();

      const inputEl = (e.target as HTMLElement) || adapter.findInput();
      const finalText = await processPasteText(text);
      if (finalText === null || !inputEl) return;
      adapter.insertText(inputEl, finalText);
    }

    document.addEventListener('paste', onPaste, true);
    document.addEventListener('beforeinput', onBeforeInput as unknown as EventListener, true);

    console.info('[redact] attached to', location.hostname);
  },
});
