import { getAdapter, HOST_MATCHES, type SiteAdapter } from '@/lib/sites';
import {
  showLoadingIndicator, removeLoadingIndicator,
  showWarnBanner, showBlockModal, showBlockInlineConfirm, showRedactionToast,
} from '@/lib/ui';
import { effectiveSettings, inCooldown, markCooldown } from '@/lib/settings';
import { redactSpans, blockSpans, warnSpans } from '@/lib/redact';
import type { DetectionSpan } from '@/lib/tiers';
import '@/assets/content.css';

// Vite bundles the worker as a separate chunk. `?worker&url` returns the path
// to that chunk (e.g. "/assets/inference-worker-XXXX.js"). We then prepend the
// extension's origin via browser.runtime.getURL — content scripts run in the
// host page's context, so a bare path would resolve against claude.ai, not the
// extension, and 404.
import workerUrlPath from '@/lib/inference-worker.ts?worker&url';

export default defineContentScript({
  matches: HOST_MATCHES,
  cssInjectionMode: 'manifest',
  main() {
    const found = getAdapter();
    if (!found) {
      console.warn('[redact] no adapter for', location.hostname);
      return;
    }
    // Re-bind to a non-null const so closures below don't lose narrowing.
    const adapter: SiteAdapter = found;

    // Minimum paste length that triggers detection. Set low enough that short
    // PII (SSN ~11 chars, phone ~12 chars, short emails ~10 chars) still gets
    // scanned. The lower bound exists to avoid spinning up the worker for
    // one-word pastes like "yes" or "ok".
    const MIN_PASTE_LENGTH = 8;

    // ── Worker setup ────────────────────────────────────────────────────────
    // MV3 quirk: a content script can't construct a Worker pointing at a
    // chrome-extension:// URL — Chrome blocks it as cross-origin. The
    // workaround: fetch the bundled worker file (allowed because it's in
    // web_accessible_resources), wrap the source in a Blob, and spawn from
    // the Blob URL. Blob inherits the host page's origin, so the cross-origin
    // restriction doesn't apply to the constructor.
    let worker: Worker | null = null;
    let workerInitPromise: Promise<Worker> | null = null;
    let nextRequestId = 1;
    const pendingRequests = new Map<number, (r: { detections?: DetectionSpan[]; error?: string }) => void>();

    async function getWorker(): Promise<Worker> {
      if (worker) return worker;
      if (workerInitPromise) return workerInitPromise;

      workerInitPromise = (async () => {
        // Cast: the worker chunk path is generated by Vite at build time and isn't
        // in WXT's static PublicPath union. Same for /model/ and /wasm/ below — the
        // model dir holds the directory base path (transformers.js appends filenames),
        // and /wasm/ is populated by the vite-plugin-static-copy build step.
        const getURL = (p: string) => browser.runtime.getURL(p as never);
        const workerUrl = getURL(workerUrlPath);
        const response = await fetch(workerUrl);
        const code = await response.text();
        const blob = new Blob([code], { type: 'text/javascript' });
        const blobUrl = URL.createObjectURL(blob);

        // Some hosts ship CSP rules that disallow blob: workers (e.g. Gemini's
        // `worker-src *` excludes blob: and chrome-extension: per spec). The
        // Worker constructor itself succeeds, but the script load fails async
        // and an error event fires shortly after. We race the init against
        // that error: if no error within INIT_GRACE_MS, the worker is alive.
        // Canonical MV3 fix for CSP-strict hosts is to move inference into an
        // Offscreen Document — leaving that for a follow-up.
        const w = new Worker(blobUrl, { type: 'module' });

        const INIT_GRACE_MS = 150;
        let initSettled = false;
        const initOutcome = await new Promise<'ok' | 'csp-blocked'>((resolve) => {
          w.addEventListener('error', () => {
            if (!initSettled) {
              initSettled = true;
              resolve('csp-blocked');
            }
            // Post-init errors are surfaced through the long-lived listener below.
          });
          w.postMessage({
            type: 'init',
            modelUrl: getURL('/model/'),
            wasmPaths: getURL('/wasm/'),
          });
          setTimeout(() => {
            if (!initSettled) {
              initSettled = true;
              resolve('ok');
            }
          }, INIT_GRACE_MS);
        });

        if (initOutcome === 'csp-blocked') {
          console.warn(
            `[redact] cannot run inference on ${location.hostname} — host CSP ` +
            `blocks blob: workers. Paste detection is disabled on this site.`,
          );
          w.terminate();
          throw new Error('worker-blocked-by-csp');
        }

        w.addEventListener('message', (e: MessageEvent) => {
          const { id, detections, error } = e.data;
          const resolve = pendingRequests.get(id);
          if (!resolve) return;
          pendingRequests.delete(id);
          resolve({ detections, error });
        });
        w.addEventListener('error', (e) => {
          console.error('[redact] worker error:', e);
        });

        worker = w;
        return w;
      })();

      return workerInitPromise;
    }

    async function runInference(text: string): Promise<{ detections?: DetectionSpan[]; error?: string }> {
      const w = await getWorker();
      return new Promise((resolve) => {
        const id = nextRequestId++;
        pendingRequests.set(id, resolve);
        w.postMessage({ type: 'infer', id, text });
      });
    }

    // ── Core handler ────────────────────────────────────────────────────────
    // Runs the model + UI flow on a chunk of pasted text. Returns:
    //   - { text } — text the caller should insert (possibly redacted)
    //   - { text, redactedBlocks } — auto-redact mode: caller inserts `text`
    //     (already redacted) and shows the informational redact toast.
    //   - null — the user cancelled, don't insert anything
    interface ProcessResult {
      text: string;
      redactedBlocks?: DetectionSpan[];
    }
    async function processPasteText(pastedText: string): Promise<ProcessResult | null> {
      const settings = await effectiveSettings(location.hostname);
      if (!settings.enabled) return { text: pastedText };

      if (!pastedText || pastedText.length < MIN_PASTE_LENGTH) return { text: pastedText };

      showLoadingIndicator();
      let detections: DetectionSpan[] = [];
      let workerUnavailable = false;
      try {
        const result = await runInference(pastedText);
        if (result.error) console.error('[redact] inference error:', result.error);
        detections = result.detections || [];
      } catch (err) {
        // Most commonly: host CSP blocked worker creation (see getWorker). The
        // promise is also cached — once it rejects, subsequent calls re-throw
        // immediately, so we won't spam the user with the warning.
        workerUnavailable = true;
      }
      removeLoadingIndicator();

      // If the worker couldn't load on this host, pass the paste through
      // unchanged rather than swallowing it.
      if (workerUnavailable) return { text: pastedText };

      // ↓ used by both auto-redact and cooldown to surface the toast post-insert.

      // Apply per-type tier overrides from user settings. The worker uses the
      // built-in NER_TIER defaults; we re-tag here so the user's preferences
      // (e.g. "treat email as block, not warn") drive blockSpans/warnSpans.
      if (settings.tierOverrides && Object.keys(settings.tierOverrides).length > 0) {
        detections = detections.map((d) => {
          const override = settings.tierOverrides[d.label];
          return override ? { ...d, tier: override } : d;
        });
      }

      const blocks = blockSpans(detections);
      const warns = warnSpans(detections);

      let finalText = pastedText;
      let redactedBlocks: DetectionSpan[] | undefined;

      if (blocks.length > 0) {
        const mode = settings.blockBehavior;
        const isSilentRedact =
          mode === 'auto-redact' ||
          (mode === 'cooldown' && inCooldown(location.hostname, settings.cooldownMinutes));

        if (isSilentRedact) {
          // Caller will insert this text and then show the redact toast.
          finalText = redactSpans(pastedText, blocks);
          redactedBlocks = blocks;
        } else {
          // 'modal' = full-screen overlay; 'confirm' (default) = compact top-of-page prompt.
          // 'cooldown' (when *not* in cooldown window) prompts the first time, then markCooldown
          // makes future pastes within the window go silent.
          const ask = mode === 'modal' ? showBlockModal : showBlockInlineConfirm;
          const decision = await ask(blocks);
          if (mode === 'cooldown') markCooldown(location.hostname);
          if (decision === 'cancel') return null;
          if (decision === 'redact') finalText = redactSpans(pastedText, blocks);
        }
      }

      if (warns.length > 0 && settings.warnBehavior === 'banner') {
        showWarnBanner(warns, settings.warnAutoDismissSec * 1000);
      }

      return { text: finalText, redactedBlocks };
    }

    // ── Listener strategy ───────────────────────────────────────────────────
    // We attach at `document` capture phase to catch paste events regardless
    // of which element is focused. Two event types because different editors
    // dispatch different events:
    //
    //   `paste`        — fires on simple <textarea> and most contenteditable
    //                    setups (ChatGPT, Gemini). clipboardData is sync.
    //   `beforeinput`  — fires for *any* programmatic edit including paste
    //                    on Lexical/ProseMirror/Slate editors that swallow
    //                    native paste (Claude). For inputType='insertFromPaste'
    //                    the inserted text is in `event.data`.

    async function onPaste(e: ClipboardEvent) {
      // Ignore synthetic paste events. Some adapters (Perplexity, anything
      // Lexical-based) re-insert the cleaned text by dispatching a synthetic
      // ClipboardEvent('paste'); without this guard, our own listener would
      // catch that re-paste, re-run inference, re-redact, and loop forever.
      // `isTrusted` is browser-enforced and false for any event we created.
      if (!e.isTrusted) return;

      const text = e.clipboardData?.getData('text') || '';
      if (text.length < MIN_PASTE_LENGTH) return;
      e.preventDefault();
      e.stopImmediatePropagation();

      const inputEl = (e.target as HTMLElement) || adapter.findInput();
      const result = await processPasteText(text);
      if (result === null || !inputEl) return;
      adapter.insertText(inputEl, result.text);
      if (result.redactedBlocks) showRedactionToast(result.redactedBlocks);
    }

    async function onBeforeInput(e: InputEvent) {
      // Same isTrusted guard as onPaste — synthetic insertions must not re-enter.
      if (!e.isTrusted) return;
      if (e.inputType !== 'insertFromPaste') return;

      const text = (e as any).data || e.dataTransfer?.getData('text') || '';
      if (text.length < MIN_PASTE_LENGTH) return;
      e.preventDefault();
      e.stopImmediatePropagation();

      const inputEl = (e.target as HTMLElement) || adapter.findInput();
      const result = await processPasteText(text);
      if (result === null || !inputEl) return;
      adapter.insertText(inputEl, result.text);
      if (result.redactedBlocks) showRedactionToast(result.redactedBlocks);
    }

    document.addEventListener('paste', onPaste, true);
    document.addEventListener('beforeinput', onBeforeInput as unknown as EventListener, true);

  },
});
